name: Run Robot API tests
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Robot-API-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "robot ./python_robot_api/Get_Currency_Rate_data.robot"
      - run: python --version
      - run: python -m pip install robotframework
      - run: python -m robot --version
      - run: python -m pip robotframework-requests
      - run: python -m robot ./python_robot_api/Get_Currency_Rate_data.robot
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
